name: CI

on: [push]
env: 
  MSG: Hello

jobs:
  
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Run a one-line script
      run: echo $MSG
    - name: Maybe
      if: $NOMSG
      run: echo Maybe: $NOMSG






























