name: CI

on: [push]
env: 
  MSG: Hello
  BOOLEAN: true

jobs:
  
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Run a one-line script
      run: echo $MSG
    - name: Maybe
      if: env.MSG
      run: echo Maybe $NOMSG
    - name: Maybe
      if: env.NOMSG
      run: echo Maybe $NOMSG
    - name: Boolean
      if: env.BOOLEAN
      run: echo Boolean $BOOLEAN



























