name: CI

on: [push]
env: 
  MSG: Hello
  BOOLEAN: true
  NOTBOOLEAN: false
  EMPTY: ""

jobs:
  
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Run a one-line script
      run: echo $MSG
    - name: String
      if: env.MSG
      run: echo String $NOMSG
    - name: String matches
      if: env.MSG == "Hello"
      run: echo String matches Hello
    - name: No string matches
      if: env.MSG == "Nope"
      run: echo String matches Nope
    - name: No such env
      if: env.NOMSG
      run: echo No env $NOMSG
    - name: Boolean True
      if: env.BOOLEAN
      run: echo Boolean true $BOOLEAN
    - name: Boolean false
      if: env.NOTBOOLEAN
      run: echo Boolean false $NOTBOOLEAN
    - name: Empty string
      if: evn.EMPTY
      run: echo Empty string

























